### ISSUE TITLE
Crash right when right-clicking Fusion Furnace

### ISSUE THREAD

**Issue by ChromaPIE** [Sinhika/Fusion#12]
crashes before the GUI opens.

CR: https://paste.ubuntu.com/p/yBy5GRXX9G/

**Comment by Sinhika** [comment]
1. I cannot duplicate this bug.
2. I noticed that you are using Optifine. Please test without Optifine; most mod developers, including myself, will not support or further investigate bugs if Optifine is in use, because Optifine is a closed-source mod that mucks about with the Forge and Minecraft internals and is not necessarily compatible with any Forge mod.

**Comment by ChromaPIE** [comment]
Tried without OptiFine. Crash still happened but this time the game was unable to call Not Enough Crashes, but shut itself down. Checked the log and here is the problematic part: https://paste.ubuntu.com/p/dcxsNhySK8/

**Comment by ChromaPIE** [comment]
Think I've found where the problem is. In the GUI of the Fusion Furnace the name of the block was split into two parts, one on the left and the other right. When the language was set to English, Spanish and French, issue won't happen, this may because the name, Fusion Furnace, in these three languages, all have one or two **spaces** in, but in Simplified/Traditional Chinese there's **no space**, making it unable to be split into two parts, causing the problem. So would you make independent keys, left one and right one, for the displayed name in the GUI? Or any other better solutions. Thanks.

To duplicate: Switch to Simplified/Traditional Chinese, displayed as 简体中文 (中国) or 繁體中文 (台灣).

Also I wanna ask that has Fusion already support CrT?

**Comment by Sinhika** [comment]
Nice catch.  Internationalization is always tricky for programmers who speak primarily one language, like myself, because we are prone to making assumptions about strings that may not apply in all languages. I'm going to see if the other furnaces (Netherrocks' Nether Furnace, and Simple Machines furnaces) have the same issue.

What is CrT?

**Comment by Sinhika** [comment]
Fixed by commit 0d2f1ae06196809aff0ec10d7dab705f0a25db5a, Fusion v1.16.5-2.7.2.1

**Comment by ChromaPIE** [comment]
Sorry for not making it clear enough. CrT is CraftTweaker, supporting CrT will allow modpackers to add/remove recipes of those working devices to better design the pack. Recipes are already tweakable via datapack but a CrT support would make it even better.
